-- Migrácia 016: Prijemky (inbound_receipts) a ich položky

CREATE TABLE IF NOT EXISTS inbound_receipts (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  local_id INTEGER NOT NULL,
  receipt_number TEXT NOT NULL,
  created_at TEXT,
  supplier_name TEXT,
  notes TEXT,
  username TEXT,
  prices_include_vat INTEGER DEFAULT 0,
  vat_applies_to_all INTEGER DEFAULT 0,
  vat_rate NUMERIC(5,2),
  status TEXT DEFAULT 'rozpracovany',
  invoice_number TEXT,
  warehouse_id INTEGER,
  source_warehouse_id INTEGER,
  movement_type_code TEXT DEFAULT 'STANDARD',
  je_vysporiadana INTEGER DEFAULT 0,
  linked_stock_out_local_id INTEGER,
  cost_distribution_method TEXT,
  submitted_at TEXT,
  approved_at TEXT,
  approver_username TEXT,
  approver_note TEXT,
  rejected_at TEXT,
  rejection_reason TEXT,
  reversed_at TEXT,
  reversed_by_username TEXT,
  reverse_reason TEXT,
  stock_applied INTEGER DEFAULT 0,
  supplier_id INTEGER,
  supplier_ico TEXT,
  supplier_dic TEXT,
  supplier_address TEXT,
  delivery_note_number TEXT,
  po_number TEXT,
  UNIQUE(user_id, local_id)
);

CREATE TABLE IF NOT EXISTS inbound_receipt_items (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  local_id INTEGER NOT NULL,
  receipt_local_id INTEGER NOT NULL,
  product_unique_id TEXT,
  product_name TEXT,
  plu TEXT,
  qty NUMERIC(12,3),
  unit TEXT,
  unit_price NUMERIC(12,4),
  vat_percent NUMERIC(5,2),
  allocated_cost NUMERIC(12,4),
  total_price NUMERIC(12,4),
  batch_number TEXT,
  expiry_date TEXT,
  UNIQUE(user_id, local_id)
);

CREATE TABLE IF NOT EXISTS receipt_acquisition_costs (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  local_id INTEGER NOT NULL,
  receipt_local_id INTEGER NOT NULL,
  cost_type TEXT,
  description TEXT,
  amount_without_vat NUMERIC(12,4),
  vat_percent NUMERIC(5,2),
  amount_with_vat NUMERIC(12,4),
  cost_supplier_name TEXT,
  document_number TEXT,
  sort_order INTEGER DEFAULT 0,
  UNIQUE(user_id, local_id)
);
